FROM node:12.15.0 AS build
RUN mkdir -p /usr/src/klnet.owner.web
WORKDIR /usr/src/klnet.owner.web
COPY material-react-mobx/package.json ./
RUN yarn install
COPY material-react-mobx .
RUN yarn build

RUN mkdir -p /usr/src/klnet.owner.weidong
WORKDIR /usr/src/klnet.owner.weidong
COPY klnet.owner.weidong/package.json ./
RUN yarn install
COPY klnet.owner.weidong .
RUN yarn build

FROM nginx:1.16.1
# RUN rm -rf /etc/nginx/conf.d
COPY ./conf.d/default.conf /etc/nginx/conf.d/default.conf
# COPY ./conf.d/nginx.conf /etc/nginx/conf.d/nginx.conf
COPY ./ssl /usr/local/ssl/
COPY --from=build /usr/src/klnet.owner.web/build /usr/share/nginx/html/
COPY --from=build /usr/src/klnet.owner.weidong/build /usr/share/nginx/weidong/


RUN mkdir -p /usr/src/klnet.owner.web
RUN mkdir -p /usr/src/klnet.owner.weidong
COPY --from=build /usr/src/klnet.owner.web /usr/src/klnet.owner.web/
COPY --from=build /usr/src/klnet.owner.weidong /usr/src/klnet.owner.weidong/

RUN apt-get update

EXPOSE 80 443
CMD ["nginx","-g","daemon off;"]